name: First Workflow
on: workflow_dispatch
jobs:
  myfirstjob:
    runs-on: ubuntu-24.04
    steps:
      - name: print the statement
        run: echo "This is my first job created to learn gha."
      

